name: Compatibility report
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - ".github/workflows/compat.yml"
jobs:
  env-report:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Show environment details
        shell: bash
        run: |
          python -c "import sys, platform; print(sys.version); print(platform.platform())"
          echo "OS: ${{ runner.os }}"
