name: Lint
on:
  push:
    branches: [ master ]
    paths:
      - "**/*.py"
      - "**/*.ipynb"
      - ".github/workflows/lint.yml"
  pull_request:
    paths:
      - "**/*.py"
      - "**/*.ipynb"
      - ".github/workflows/lint.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ruff nbqa
      - name: Ruff (Python files)
        run: ruff check .
      - name: Ruff (Notebooks via nbqa)
        run: nbqa ruff .
